workflows:
  android:
    name: Flutter Android APK
    max_build_duration: 30
    instance_type: mac_mini
    scripts:
      - name: 构建 Release APK
        script: |
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
