workflows:
  android:
    name: Android Release Build
    scripts:
      - name: 获取依赖
        script: flutter pub get
      - name: 构建 Release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
